name: Build, Test and Deploy React Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: 🏗️ Build on Node.js 24.x
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

    steps:
      - name: 👯‍♂️ Clone repository
        uses: actions/checkout@v4
      - name: Install Node.js 24.x and pnpm
        uses: ./.github/actions/install-node
      - name: 📑 Generate JSDoc documentation
        run: pnpm jsdoc
      - name: 🧰 Build
        id: build
        run: pnpm run build --if-present
      - name: 🗒️ Build report
        if: always()
        run: |
          echo "Node.js version: $(node -v)"
          if [[ ${{ steps.build.outcome }} == "success" ]]; then
            echo "✅ Build succeeded"
          else
            echo "❌ Build failed"
          fi
      - name: 🔧 Setup pages
        id: pages
        uses: actions/configure-pages@v3
      - name: 📤 Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  test:
    name: 🧪 Test on Node.js 24.x
    runs-on: ubuntu-latest

    steps:
      - name: 👯‍♂️ Clone repository
        uses: actions/checkout@v4
      - name: Install Node.js 24.x and pnpm
        uses: ./.github/actions/install-node
      - name: 🧪 Integration Tests
        id: int-test
        run: pnpm test
      - name: 🗒️ Test report
        if: always()
        run: |
          echo "Node.js version: $(node -v)"
          if [[ ${{ steps.int-test.outcome }} == "success" ]]; then
            echo "✅ Integration Tests passed"
          else
            echo "❌ Integration Tests failed"
          fi
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  e2e:
    name: 🎭 End-to-End Tests
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

    steps:
      - name: 👯‍♂️ Clone repository
        uses: actions/checkout@v4
      - name: Install Node.js 24.x and pnpm
        uses: ./.github/actions/install-node

      - name: 🔨 Build for E2E
        run: PUBLIC_URL=/ pnpm run build
      - name: 📦 Install Cypress binary manually
        run: pnpm exec cypress install
      - name: 🎭 Run e2e tests with Cypress
        id: e2e-test
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: npx serve -s build -l 3000
          wait-on: "http://localhost:3000"
      - name: 🗒️ E2E Test report
        if: always()
        run: |
          echo "Node.js version: $(node -v)"
          if [[ ${{ steps.e2e-test.outcome }} == "success" ]]; then
            echo "✅ End-to-End Tests passed"
          else
            echo "❌ End-to-End Tests failed"
          fi

  deploy:
    name: 🚀 Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    needs: [build, test, e2e]
    steps:
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  publish:
    name: 📦 Publish to npm
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: 👯‍♂️ Clone repository
        uses: actions/checkout@v4
      - name: Install Node.js 24.x and pnpm
        uses: ./.github/actions/install-node
      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: 📌 Version Bump
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "yoann.ar.pro@gmail.com"
          pnpm version patch
      - name: 📦 Publish to npm
        run: |
          pnpm build:npm
          pnpm publish
          git add . 
          git commit -m "updated version"
          git push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
